//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lava3.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lava3.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMMERCIAL CARD.
        /// </summary>
        internal static string Category_CommercialCard {
            get {
                return ResourceManager.GetString("Category_CommercialCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string ColumnHeader_Category {
            get {
                return ResourceManager.GetString("ColumnHeader_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit.
        /// </summary>
        internal static string ColumnHeader_Credit {
            get {
                return ResourceManager.GetString("ColumnHeader_Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        internal static string ColumnHeader_Customer {
            get {
                return ResourceManager.GetString("ColumnHeader_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Funds Recieved.
        /// </summary>
        internal static string ColumnHeader_DateFundsRecieved {
            get {
                return ResourceManager.GetString("ColumnHeader_DateFundsRecieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Rate.
        /// </summary>
        internal static string ColumnHeader_DayRate {
            get {
                return ResourceManager.GetString("ColumnHeader_DayRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days Invoiced.
        /// </summary>
        internal static string ColumnHeader_DaysInvoiced {
            get {
                return ResourceManager.GetString("ColumnHeader_DaysInvoiced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days to pay.
        /// </summary>
        internal static string ColumnHeader_DaysToPay {
            get {
                return ResourceManager.GetString("ColumnHeader_DaysToPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit.
        /// </summary>
        internal static string ColumnHeader_Debit {
            get {
                return ResourceManager.GetString("ColumnHeader_Debit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string ColumnHeader_Description {
            get {
                return ResourceManager.GetString("ColumnHeader_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours Invoiced.
        /// </summary>
        internal static string ColumnHeader_HoursInvoiced {
            get {
                return ResourceManager.GetString("ColumnHeader_HoursInvoiced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice.
        /// </summary>
        internal static string ColumnHeader_Invoice {
            get {
                return ResourceManager.GetString("ColumnHeader_Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Amount.
        /// </summary>
        internal static string ColumnHeader_InvoiceAmount {
            get {
                return ResourceManager.GetString("ColumnHeader_InvoiceAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Date.
        /// </summary>
        internal static string ColumnHeader_InvoiceDate {
            get {
                return ResourceManager.GetString("ColumnHeader_InvoiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string ColumnHeader_Notes {
            get {
                return ResourceManager.GetString("ColumnHeader_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Paid.
        /// </summary>
        internal static string ColumnHeader_TotalPaid {
            get {
                return ResourceManager.GetString("ColumnHeader_TotalPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V.A.T..
        /// </summary>
        internal static string ColumnHeader_VAT {
            get {
                return ResourceManager.GetString("ColumnHeader_VAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance At start of year.
        /// </summary>
        internal static string DescriptionKey_BalanceAtStartOfYear {
            get {
                return ResourceManager.GetString("DescriptionKey_BalanceAtStartOfYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAYMENTS MADE BY DIRECTOR PRIVATELY/CASH.
        /// </summary>
        internal static string DescriptionKey_Expenses {
            get {
                return ResourceManager.GetString("DescriptionKey_Expenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SALES INVOICES.
        /// </summary>
        internal static string DescriptionKey_SalesInvoices {
            get {
                return ResourceManager.GetString("DescriptionKey_SalesInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BANK ACCOUNT PAYMENTS.
        /// </summary>
        internal static string DescriptionKey_Summary {
            get {
                return ResourceManager.GetString("DescriptionKey_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totals.
        /// </summary>
        internal static string DescriptionKey_Totals {
            get {
                return ResourceManager.GetString("DescriptionKey_Totals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Categories could be found.
        /// </summary>
        internal static string Error_NoCategoriesCouldBeFound {
            get {
                return ResourceManager.GetString("Error_NoCategoriesCouldBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If applicable.
        /// </summary>
        internal static string IfApplicable {
            get {
                return ResourceManager.GetString("IfApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subsistence.
        /// </summary>
        internal static string SumaryLabel_Subsistence {
            get {
                return ResourceManager.GetString("SumaryLabel_Subsistence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available days.
        /// </summary>
        internal static string Summary_AvailableDays {
            get {
                return ResourceManager.GetString("Summary_AvailableDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days Driven.
        /// </summary>
        internal static string Summary_DaysDriven {
            get {
                return ResourceManager.GetString("Summary_DaysDriven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days Subsistance (card).
        /// </summary>
        internal static string Summary_DaysSubsistanceCard {
            get {
                return ResourceManager.GetString("Summary_DaysSubsistanceCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days Subsistance (cash).
        /// </summary>
        internal static string Summary_DaysSubsistanceCash {
            get {
                return ResourceManager.GetString("Summary_DaysSubsistanceCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days Train.
        /// </summary>
        internal static string Summary_DaysTrain {
            get {
                return ResourceManager.GetString("Summary_DaysTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days Traveled.
        /// </summary>
        internal static string Summary_DaysTraveled {
            get {
                return ResourceManager.GetString("Summary_DaysTraveled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage Driven.
        /// </summary>
        internal static string Summary_PercentageDriven {
            get {
                return ResourceManager.GetString("Summary_PercentageDriven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage Train.
        /// </summary>
        internal static string Summary_PercentageTrain {
            get {
                return ResourceManager.GetString("Summary_PercentageTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage Traveled.
        /// </summary>
        internal static string Summary_PercentageTraveled {
            get {
                return ResourceManager.GetString("Summary_PercentageTraveled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage worked.
        /// </summary>
        internal static string Summary_PercentageWorked {
            get {
                return ResourceManager.GetString("Summary_PercentageWorked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoiced days.
        /// </summary>
        internal static string SummaryLabel_InvoicedDays {
            get {
                return ResourceManager.GetString("SummaryLabel_InvoicedDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banks balance and calculated balance do not match.
        /// </summary>
        internal static string Validation_BalancesNotMatch {
            get {
                return ResourceManager.GetString("Validation_BalancesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not resolve hyperlink..
        /// </summary>
        internal static string Validation_CannotResolveHyperLink {
            get {
                return ResourceManager.GetString("Validation_CannotResolveHyperLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Missing.
        /// </summary>
        internal static string Validation_CategoryMissing {
            get {
                return ResourceManager.GetString("Validation_CategoryMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate description..
        /// </summary>
        internal static string Validation_DuplicateDescription {
            get {
                return ResourceManager.GetString("Validation_DuplicateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate notes..
        /// </summary>
        internal static string Validation_DuplicateNotes {
            get {
                return ResourceManager.GetString("Validation_DuplicateNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreditCard.
        /// </summary>
        internal static string WorkSheelLabel_CreditCard {
            get {
                return ResourceManager.GetString("WorkSheelLabel_CreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual Summary.
        /// </summary>
        internal static string WorkSheetLabel_AnnualSummary {
            get {
                return ResourceManager.GetString("WorkSheetLabel_AnnualSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Mileage.
        /// </summary>
        internal static string WorkSheetLabel_CarMilage {
            get {
                return ResourceManager.GetString("WorkSheetLabel_CarMilage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category LookUp.
        /// </summary>
        internal static string WorkSheetLabel_CategoryLookup {
            get {
                return ResourceManager.GetString("WorkSheetLabel_CategoryLookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HSBC.
        /// </summary>
        internal static string WorksheetLabel_CurrentAccount {
            get {
                return ResourceManager.GetString("WorksheetLabel_CurrentAccount", resourceCulture);
            }
        }
    }
}
