//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lava3.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lava3.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit.
        /// </summary>
        internal static string ColumnHeader_Credit {
            get {
                return ResourceManager.GetString("ColumnHeader_Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit.
        /// </summary>
        internal static string ColumnHeader_Debit {
            get {
                return ResourceManager.GetString("ColumnHeader_Debit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string ColumnHeader_Notes {
            get {
                return ResourceManager.GetString("ColumnHeader_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance At start of year.
        /// </summary>
        internal static string DescriptionKey_BalanceAtStartOfYear {
            get {
                return ResourceManager.GetString("DescriptionKey_BalanceAtStartOfYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAYMENTS MADE BY DIRECTOR PRIVATELY/CASH&quot;.
        /// </summary>
        internal static string DescriptionKey_Expenses {
            get {
                return ResourceManager.GetString("DescriptionKey_Expenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SALES INVOICES.
        /// </summary>
        internal static string DescriptionKey_SalesInvoices {
            get {
                return ResourceManager.GetString("DescriptionKey_SalesInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BANK ACCOUNT PAYMENTS.
        /// </summary>
        internal static string DescriptionKey_Summary {
            get {
                return ResourceManager.GetString("DescriptionKey_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totals.
        /// </summary>
        internal static string DescriptionKey_Totals {
            get {
                return ResourceManager.GetString("DescriptionKey_Totals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Categories could be found.
        /// </summary>
        internal static string Error_NoCategoriesCouldBeFound {
            get {
                return ResourceManager.GetString("Error_NoCategoriesCouldBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banks balance and calculated balance do not match.
        /// </summary>
        internal static string Validation_BalancesNotMatch {
            get {
                return ResourceManager.GetString("Validation_BalancesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not resolve hyperlink..
        /// </summary>
        internal static string Validation_CannotResolveHyperLink {
            get {
                return ResourceManager.GetString("Validation_CannotResolveHyperLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CategoryMissing.
        /// </summary>
        internal static string Validation_CategoryMissing {
            get {
                return ResourceManager.GetString("Validation_CategoryMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate description..
        /// </summary>
        internal static string Validation_DuplicateDescription {
            get {
                return ResourceManager.GetString("Validation_DuplicateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate notes..
        /// </summary>
        internal static string Validation_DuplicateNotes {
            get {
                return ResourceManager.GetString("Validation_DuplicateNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreditCard.
        /// </summary>
        internal static string WorkSheelLabel_CreditCard {
            get {
                return ResourceManager.GetString("WorkSheelLabel_CreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual Summary.
        /// </summary>
        internal static string WorkSheetLabel_AnnualSummary {
            get {
                return ResourceManager.GetString("WorkSheetLabel_AnnualSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Mileage.
        /// </summary>
        internal static string WorkSheetLabel_CarMilage {
            get {
                return ResourceManager.GetString("WorkSheetLabel_CarMilage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category LookUp.
        /// </summary>
        internal static string WorkSheetLabel_CategoryLookup {
            get {
                return ResourceManager.GetString("WorkSheetLabel_CategoryLookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HSBC.
        /// </summary>
        internal static string WorksheetLabel_CurrentAccount {
            get {
                return ResourceManager.GetString("WorksheetLabel_CurrentAccount", resourceCulture);
            }
        }
    }
}
